spring:
  application:
    name: eureka

eureka:
  dashboard:
    enabled: false


server:
  port: 8761

---
spring:
  profiles: dev
   
eureka:
  dashboard:
    enabled: true
  client:
    fetch-registry: false
    register-with-eureka: false